<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot">
    <xacro:include filename="common_properties.xacro" />
    <xacro:property name="base_length" value="4" />
    <xacro:property name="base_width" value="2" />
    <xacro:property name="base_height" value="1" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />
  <!-- Base Link -->
    <link name="base_footprint" />
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}"
                           xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </link>
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius+1}" rpy="0 0 0"/>
    </joint>

   <xacro:macro name="wheel" params="dir">
  <link name="${dir}_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="0.01" length="0.2"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <cylinder radius="0.01" length="0.2"/>
      </geometry>      
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <link name="${dir}_gear_small">
    <visual>
      <geometry>
        <mesh filename="package://my_robot_description/meshes/gear_small.stl" scale="0.005 0.005 0.005"/>  
      </geometry>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>  
      </material>
    </visual>
    <collision>
        <geometry>
        <cylinder radius="0.1" length="0.2"/> 
      </geometry>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

<!--GEAR QUADS-->
  <xacro:macro name="quad" params="num">
    <link name="${dir}_quad${num}">
      <visual>
        <geometry>
          <mesh filename="package://my_robot_description/meshes/wheel_quad.stl" scale="0.005 0.005 0.005"/>  
        </geometry>
        <material name="gray">
          <color rgba="0.5 0.5 0.5 1"/>  
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://my_robot_description/meshes/wheel_quad.stl" scale="0.005 0.005 0.005"/>  
        </geometry>        
      </collision>
      <inertial>
        <mass value="1.0"/>
        <inertia  ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
      </inertial>
    </link>
  </xacro:macro>



<!-- HANDLE -->
  <xacro:macro name="handle" params="num">
    <link name="${dir}_handle${num}">
      <visual>
        <geometry>
          <mesh filename="package://my_robot_description/meshes/handle_v1.stl" scale="0.005 0.005 0.005"/>  
        </geometry>
        <material name="gray">
          <color rgba="0.5 0.5 0.5 1"/>  
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="0.01" length="0.2"/>  
        </geometry>
      </collision>
      <inertial>
        <mass value="0.3"/>
        <inertia  ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
      </inertial>
    </link>
  </xacro:macro>

  <!-- FOR PLUS DESIGN -->
  <link name="${dir}_plus">
    <visual>
      <geometry>
        <mesh filename="package://my_robot_description/meshes/bracket_v1.stl" scale="0.005 0.005 0.005"/>  
      </geometry>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>  
      </material>
    </visual>
    <collision>
        <geometry>
        <cylinder radius="0.01" length="0.2"/>  
      </geometry>
    </collision>
    <inertial>
      <mass value="0.4"/>
      <inertia  ixx="0.02" ixy="0.0" ixz="0.0" iyy="0.02" iyz="0.0" izz="0.02"/>
    </inertial>
  </link>

  <joint name="${dir}_bases" type="fixed">
    <parent link="${dir}_wheel_link"/>
    <child link="${dir}_plus"/>
    <origin xyz="-0.1 -0.05 -0.16" rpy="0 0 0"/>  
  </joint>

<!-- GEAR BIG WITH HANDLE -->
  <xacro:macro name="gear_big" params="num">
    <link name="${dir}_gear_big${num}">
      <visual>
        <geometry>
          <mesh filename="package://my_robot_description/meshes/gear_big.stl" scale="0.005 0.005 0.005"/>  
        </geometry>
        <material name="gray">
          <color rgba="0.5 0.5 0.5 1"/>  
        </material>
      </visual>
      <collision>
          <geometry>
          <cylinder radius="0.1" length="0.2"/>  
        </geometry>
      </collision>
      <inertial>
        <mass value="2.0"/>
        <inertia  ixx="0.2" ixy="0.0" ixz="0.0" iyy="0.2" iyz="0.0" izz="0.2"/>
      </inertial>
    </link>
    <xacro:handle num="${num}"/>
    <joint name="gear_${dir}_handle_${num}" type="fixed">
      <parent link="${dir}_gear_big${num}"/>
      <child link="${dir}_handle${num}"/>
      <origin xyz="0.1 0.0 0.05" rpy="0.0 0.0 0.0"/>
    </joint>
    <xacro:quad num="${num}"/>
    <joint name="${dir}_pris_${num}" type="prismatic">
    <parent link="${dir}_handle${num}"/>
    <child link="${dir}_quad${num}"/>
    <origin xyz="-0.220 0.0 -0.175" rpy="0 0 -1.57"/>
    <axis xyz="0 1 0"/> 
    <limit lower="-0.4" upper="-0.163" effort="10" velocity="1.0"/>
    </joint>
  </xacro:macro>

  <xacro:gear_big num="1"/>
  <xacro:gear_big num="2"/>
  <xacro:gear_big num="3"/>
  <xacro:gear_big num="4"/>

  <!-- MOTOR CASING -->
  <link name="${dir}_motor_case">
    <visual>
      <geometry>
        <mesh filename="package://my_robot_description/meshes/motor_casing.stl" scale="0.005 0.005 0.005"/>  
      </geometry>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>  
      </material>
    </visual>
    <collision>
        <geometry>
        <cylinder radius="0.01" length="0.2"/>  
      </geometry>
    </collision>
    <inertial>
      <mass value="1.5"/>
      <inertia  ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
  </link>

  <!--FOR MOTOR AND GEAR CONNECTION-->
  <xacro:macro name="bracket2" params="num">
  <link name="${dir}_bracket2${num}">
    <visual>
      <geometry>
        <mesh filename="package://my_robot_description/meshes/bracket_v2.stl" scale="0.005 0.005 0.005"/>  
      </geometry>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>  
      </material>
    </visual>
    <collision>
            <geometry>
        <cylinder radius="0.01" length="0.2"/>  
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia  ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
  </link>
  </xacro:macro>

  <xacro:bracket2 num="1"/>
  
  <joint name="plus_joint${dir}_" type="fixed">
    <parent link="${dir}_wheel_link"/>
    <child link="${dir}_bracket21"/>
    <origin xyz="0 0 -0.05" rpy="0 0 0"/>  

  </joint>



  <joint name="base_${dir}_motor_case" type="fixed">
    <parent link="${dir}_wheel_link"/>
    <child link="${dir}_motor_case"/>
    <origin xyz="0.0 -0.15 0.0" rpy="0 0 0"/>  
  </joint>

  <joint name="base_to_${dir}_gear" type="continuous">
    <parent link="${dir}_wheel_link"/>
    <child link="${dir}_gear_small"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>  
    <axis xyz="0.0 0.0 1.0"/>
  </joint>

  <joint name="base_to_${dir}_g1" type="continuous">
    <parent link="${dir}_wheel_link"/>
    <child link="${dir}_gear_big1"/>
    <origin xyz="0 0.225 0" rpy="0 0 -1.57"/>  
    <axis xyz="0.0 0.0 1.0"/>
  </joint>

  <joint name="base_to_${dir}_g2" type="continuous">
    <parent link="${dir}_wheel_link"/>
    <child link="${dir}_gear_big2"/>
    <origin xyz="0 -0.225 0" rpy="0 0 1.57"/>  
    <axis xyz="0.0 0.0 1.0"/>
  </joint>

  <joint name="base_to_${dir}_g3" type="continuous">
    <parent link="${dir}_wheel_link"/>
    <child link="${dir}_gear_big3"/>
    <origin xyz="0.225 -0.0 0" rpy="0 0 3.14"/>  
    <axis xyz="0.0 0.0 1.0"/>
  </joint>

  <joint name="base_to_${dir}_g4" type="continuous">
    <parent link="${dir}_wheel_link"/>
    <child link="${dir}_gear_big4"/>
    <origin xyz="-0.225 0.0 0" rpy="0 0 0.0"/>  
    <axis xyz="0.0 0.0 1.0"/>
  </joint>
  </xacro:macro>



  <xacro:wheel dir="right"/>
  <xacro:wheel dir="left"/>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="1.57 0 0" />
        <axis xyz="0 1 0" />
    </joint>
  
    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="1.57 0 3.14" />
        <axis xyz="0 1 0" />
    </joint>


  <xacro:wheel dir="front_right"/>
  <xacro:wheel dir="front_left"/>
    <joint name="base_front_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_right_wheel_link" />
        <origin xyz="${base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="1.57 0 0" />
        <axis xyz="0 1 0" />
    </joint>
    <joint name="base_front_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_left_wheel_link" />
        <origin xyz="${base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="1.57 0 3.14" />
        <axis xyz="0 1 0" />
    </joint>
  

        <gazebo reference="base_link">
        <material>Gazebo/Blue</material>
    </gazebo>

    <gazebo reference="right_wheel_link">
        <material>Gazebo/Grey</material>
    </gazebo>
  
    <gazebo reference="left_wheel_link">
        <material>Gazebo/Grey</material>
    </gazebo>
 
    <gazebo reference="front_right_wheel_link">
        <material>Gazebo/Grey</material>
    </gazebo>

    <gazebo reference="front_left_wheel_link">
        <material>Gazebo/Grey</material>
    </gazebo>
    <gazebo>
        <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <!-- Update rate in Hz -->
            <update_rate>50</update_rate>
            <!-- wheels -->
            <left_joint>base_left_wheel_joint</left_joint>
            <right_joint>base_right_wheel_joint</right_joint>
            <!-- kinematics -->
            <wheel_separation>0.45</wheel_separation>
            <wheel_diameter>0.2</wheel_diameter>
            <!-- output -->
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>
            <odometry_topic>odom</odometry_topic>
            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_footprint</robot_base_frame>
        </plugin>
    </gazebo>
</robot>
